name: smartfleet
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:

  image_picker: ^0.6.3+4

  firebase_storage: ^3.1.3

  firebase_auth: ^0.15.5+2
  
  cloud_firestore: ^0.13.4+2

  flutter_map:

  location: ^2.5.4

  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  
  font_awesome_flutter: ^8.7.0
dependency_overrides:
  platform: ^3.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
   - assets/images/
   